# Generated by Django 3.0.5 on 2020-04-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_base',
            name='travelHistory',
            field=models.IntegerField(default=0),
        ),
    ]
