# Generated by Django 3.0.5 on 2020-04-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_auto_20200414_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_base',
            name='fever',
            field=models.CharField(choices=[(0, 'No Fever (98*F)'), (1, 'Mild Fever (100*F)'), (3, 'High Fever (103*F)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='data_base',
            name='travelHistory',
            field=models.CharField(choices=[(0, 'None'), (1, 'National'), (2, 'International'), (5, 'Covid Infected Zone ')], max_length=128),
        ),
    ]
