# Generated by Django 3.0.5 on 2020-04-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_auto_20200414_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_data',
            name='patient_status',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Suspected', 'Suspected'), ('Negative', 'Negative')], max_length=20),
        ),
    ]
